### ISSUE TITLE
Example Startup Function Not being Hit

### ISSUE THREAD

**Issue by minitriga** [jeremyschulman/slack-click#2]
I expect that the startup function will `sys.exit` but looks to skip that check for envvars.

```console
(venv) agitting@dev:~/python/slack-click/example$ ./start.sh 
INFO:     Uvicorn running on http://0.0.0.0:5000 (Press CTRL+C to quit)
INFO:     Started reloader process [10925] using statreload
Process SpawnProcess-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/home/agitting/python/slack-click/example/venv/lib/python3.8/site-packages/uvicorn/subprocess.py", line 61, in subprocess_started
    target(sockets=sockets)
  File "/home/agitting/python/slack-click/example/venv/lib/python3.8/site-packages/uvicorn/server.py", line 49, in run
    loop.run_until_complete(self.serve(sockets=sockets))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/agitting/python/slack-click/example/venv/lib/python3.8/site-packages/uvicorn/server.py", line 56, in serve
    config.load()
  File "/home/agitting/python/slack-click/example/venv/lib/python3.8/site-packages/uvicorn/config.py", line 308, in load
    self.loaded_app = import_from_string(self.app)
  File "/home/agitting/python/slack-click/example/venv/lib/python3.8/site-packages/uvicorn/importer.py", line 20, in import_from_string
    module = importlib.import_module(module_str)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "./clicker/__init__.py", line 1, in <module>
    from .main import api
  File "./clicker/main.py", line 12, in <module>
    from .app_data import api, slack_socket_handler  # noqa
  File "./clicker/app_data.py", line 21, in <module>
    slack_app = AsyncApp()
  File "/home/agitting/python/slack-click/example/venv/lib/python3.8/site-packages/slack_bolt/app/async_app.py", line 339, in __init__
    self._init_async_middleware_list(
  File "/home/agitting/python/slack-click/example/venv/lib/python3.8/site-packages/slack_bolt/app/async_app.py", line 374, in _init_async_middleware_list
    raise BoltError(error_token_required())
slack_bolt.error.BoltError: Either an env variable `SLACK_BOT_TOKEN` or `token` argument in the constructor is required.
```

**Comment by jeremyschulman** [comment]
@minitriga - apologies; was this issue resolved?
